// <auto-generated />
using MTGWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTGWebsite.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210414034718_TestCards")]
    partial class TestCards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MTGWebsite.Models.Card", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CardNumber")
                        .HasColumnType("int");

                    b.Property<string>("CardText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConvertedMana")
                        .HasColumnType("int");

                    b.Property<string>("Expansion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlavorText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Card");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CardNumber = 7,
                            CardText = "Choose one - ... ",
                            ConvertedMana = 2,
                            Expansion = "Strixhaven: School of Mages",
                            FlavorText = "None",
                            Image = "https://media.wizards.com/2021/stx/en_yh4p4W4O4x.png",
                            ManaCost = "1 Colorless, 1 White",
                            Name = "Academic Probation",
                            Rarity = "Rare",
                            Type = "Sorcery - Lesson"
                        },
                        new
                        {
                            id = 2,
                            CardNumber = 8,
                            CardText = "None",
                            ConvertedMana = 2,
                            Expansion = "Strixhaven: School of Mages",
                            FlavorText = "Ancient ruins...",
                            Image = "https://media.wizards.com/2021/stx/en_v5m1B5aTSo.png",
                            ManaCost = "1 Colorless, 1 White",
                            Name = "Ageless Guardian",
                            Rarity = "Uncommon",
                            Type = "Creature - Spirit Soldier"
                        },
                        new
                        {
                            id = 3,
                            CardNumber = 9,
                            CardText = "Target creature you...",
                            ConvertedMana = 2,
                            Expansion = "Strixhaven: School of Mages",
                            FlavorText = "I've lived too...",
                            Image = "https://media.wizards.com/2021/stx/en_2B1ejCfSFx.png",
                            ManaCost = "1 Colorless, 1 White",
                            Name = "Beaming Defiance",
                            Rarity = "Common",
                            Type = "Instant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
